name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

permissions:
  contents: write  # ✅ Allows GitHub Actions to push changes

jobs:
  build:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 for stability

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the Snake contribution graph
      - name: Generate Snake Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: developervaibhav1

      # Step 3: Ensure dist/ folder exists before deployment
      - name: Create dist directory
        run: mkdir -p dist  # ✅ Fixes "Build dir does not exist" error

      # Step 4: Show git status for debugging
      - name: Show Git Status
        run: git status

      # Step 5: Push generated snake files to the output branch
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # ✅ Ensure this branch exists

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist  # ✅ Now this folder exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
