name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Explicitly using Ubuntu 22.04 to avoid future issues

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the Snake contribution graph (without gif_out_path & svg_out_path)
      - name: Generate Snake Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: developervaibhav1

      # Step 3: Show git status for debugging
      - name: Show Git Status
        run: git status

      # Step 4: Push generated snake files to the output branch
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # Ensure your branch name is correct

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
