name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the snake SVG and GIF
      - name: Generate Snake Contribution Graph
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: developervaibhav1
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Check the git status
      - name: Show Git Status
        run: git status

      # Push changes (Ensure that the branch exists)
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # Ensure your branch is correctly named

      # Deploy to GitHub Pages
      - name: Deploy Snake Graph to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Output branch
          build_dir: dist  # Directory with snake files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

