name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours

  workflow_dispatch:  # Allows manual execution from Actions tab

permissions:
  contents: write  # Ensures GitHub Actions has write permissions

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Generate the Snake contribution graph
      - name: Generate Snake Contribution Graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg  # ✅ Fixed incorrect YAML formatting

      # Step 3: Show git status for debugging
      - name: Show Git Status
        run: git status

      # Step 4: Push the changes
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
